### ISSUE TITLE
GLib.Error: gtk-css-provider-error-quark: <data>:1:10not a number (1)

### ISSUE THREAD

**Issue by M0Rf30** [radiocicletta/idjc-x#1]
Hi, I'm trying your fork and here some issues

```
(idjc:2837): Gtk-WARNING **: Theme parsing error: <data>:1:18: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
Traceback (most recent call last):
  File "/usr/bin/idjc", line 32, in <module>
    exit(idjc.main())
  File "/usr/lib/idjc/site-packages/idjc/__init__.py", line 116, in main
    return maingui.main()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4311, in main
    run_instance = MainWindow()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 3451, in __init__
    self.player_left = IDJC_Media_Player(self.vbox3L, "left", self)
  File "/usr/lib/idjc/site-packages/idjc/playergui.py", line 4536, in __init__
    b'* { font: Sans 10 }'
GLib.Error: gtk-css-provider-error-quark: <data>:1:10not a number (1)

```

**Comment by leofiore** [comment]
Hi,

Can you please provide more informations about your environment? OS, distribution, gtk/python-gi version? Looks to me you are using an older gtk3 version.

**Comment by M0Rf30** [comment]
Arch Linux,
gtk3 3.22.5
python-gobject 3.22.0-1

**Comment by leofiore** [comment]
so, looks like a typical "it's not you baby, it's me" situation. Looking at gtk [changelog](https://abi-laboratory.pro/tracker/changelog/gtk+/3.22.5/log.html) i see this

```
Overview of Changes in GTK+ 3.21.1
==================================
[...]
* CSS:
 - Inconsistencies in font size handling have been fixed
 - The font shorthand is now parsed according to the CSS spec
```

right now debian stable uses gtk 3.14 , so this is the reason i've never had this problem. How annoying.

**Comment by leofiore** [comment]
commit 280ab4eebcd6a97c25ee206c5c6d2966e16d5cb2 should fix the problem. Please update your repository and verify it.

**Comment by M0Rf30** [comment]
fixed the previous but now:
```
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 2243, in _on_apply
    self._current = globals()[next_element_name](self._current)
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 1544, in __init__
    er.good_samplerates(channels))
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 430, in __init__
    self._spin_button = Gtk.SpinButton(adjustment)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
TypeError: cb_new_folder() missing 1 required positional argument: 'path'

(idjc:3106): Gtk-CRITICAL **: gtk_grid_attach_next_to: assertion 'sibling == NULL || _gtk_widget_get_parent (sibling) == (GtkWidget*)grid' failed

(idjc:3106): Gtk-WARNING **: Can't set a parent on a toplevel widget
song title: 

activated ch 1
activated ch 3
activated ch 4
entering stereo mode, ch 4
Traceback (most recent call last):
  File "/usr/bin/idjc", line 32, in <module>
    exit(idjc.main())
  File "/usr/lib/idjc/site-packages/idjc/__init__.py", line 116, in main
    return maingui.main()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4311, in main
    run_instance = MainWindow()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4191, in __init__
    lambda s, f: idle_add(threadslock(self.destroy))
  File "/usr/lib/python3.5/signal.py", line 48, in signal
    return _int_to_enum(handler, Handlers)
  File "/usr/lib/python3.5/signal.py", line 30, in _int_to_enum
    return enum_klass(value)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
  File "/usr/lib/python3.5/site-packages/dbus/service.py", line 786, in __repr__
    if (self._object_path is not _MANY
AttributeError: 'MainWindow' object has no attribute '_object_path'
```

**Comment by leofiore** [comment]
those two looks like two different issues. I'll open two more. Please follow me into this exciting journey.
