### ISSUE TITLE
TypeError: cb_new_folder() missing 1 required positional argument: 'path'

### ISSUE THREAD

**Issue by leofiore** [radiocicletta/idjc-x#2]
citing @M0Rf30's previous [comments](https://github.com/radiocicletta/idjc-x/issues/1#issuecomment-269199602) in #1 :

```
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 2243, in _on_apply
    self._current = globals()[next_element_name](self._current)
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 1544, in __init__
    er.good_samplerates(channels))
  File "/usr/lib/idjc/site-packages/idjc/format.py", line 430, in __init__
    self._spin_button = Gtk.SpinButton(adjustment)
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
TypeError: cb_new_folder() missing 1 required positional argument: 'path'
```

**Comment by M0Rf30** [comment]
Ok how could I help you? In the meantime, I've created a package on my distro ;)
https://aur.archlinux.org/packages/idjc-x-git/

**Comment by leofiore** [comment]
Trying the software is a valuable help from you. I would not recommend you to distribute this software as an AUR package until you haven't tested extensively. I myself consider it in an alpha/unstable stage because i couldn't test it properly.

Patches and pull requests are of course appreciated. If you are unexperienced with idjc's codebase, take your time to explore it and understand it.

**Comment by leofiore** [comment]
i suppose you tried to create a new profile, or a new record folder. Please give a try to commit 3373cd7417de0bfbdc2fff5c31273b3f8f644091 and replicate your actions. 

Please remember to do your tests in a way that is reproducible and provide more informations possible. do your tests and in case of bugs describe the steps to replicate it. If you have previously started the application, please do some tests in a clean environment, thus deleting the .config/idjc directory and restarting the application.

**Comment by M0Rf30** [comment]
idjc-x is marked as git package on AUR, so it's implicitly recommended to devs only and could only widen the user and test base. That's why I've uploaded it. 
I've removed the .config/idjc folder, installed the latest commit, restarted the software and opened the listed default profile
here the log:

```
** (idjc:19134): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-0SUEvMdYIN: Connessione rifiutata
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
callback cancelled
Traceback (most recent call last):
  File "/usr/lib/idjc/site-packages/idjc/irc.py", line 36, in <module>
    from irc import client
ImportError: No module named 'irc'
No IRC support
/usr/lib/python3.5/site-packages/gi/types.py:205: Warning: Object class idjc+preferences+AGCControl doesn't implement property 'use-action-appearance' from interface 'GtkActivatable'
  _gobject.type_register(cls, namespace.get('__gtype_name__'))
/usr/lib/python3.5/site-packages/gi/types.py:205: Warning: Object class idjc+preferences+AGCControl doesn't implement property 'related-action' from interface 'GtkActivatable'
  _gobject.type_register(cls, namespace.get('__gtype_name__'))
error getting num_micpairs
error getting num_streamers
error getting num_recorders
jack client ID: idjc_radio
launching backend
backend launch attempt 1
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
started 6 encoders, 6 streamers, 2 recorders
player read buffer allocated for 1024 frames
awaiting reply
got idjc backend ready


(idjc:19134): Gtk-WARNING **: Theme parsing error: <data>:1:12: Not using units is deprecated. Assuming 'px'.

(idjc:19134): Gtk-WARNING **: Theme parsing error: <data>:1:12: Not using units is deprecated. Assuming 'px'.

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget

(idjc:19134): Gtk-WARNING **: Theme parsing error: <data>:1:12: Not using units is deprecated. Assuming 'px'.
problem reading JACK connections files, /home/morfeo/.config/idjc/profiles/radio/ports-L0-default
threads initialised
jack sample rate is 48000
[Errno 2] File o directory non esistente: PathStr('/home/morfeo/.config/idjc/profiles/radio/s_data')

(idjc:19134): Gtk-CRITICAL **: gtk_grid_attach_next_to: assertion 'sibling == NULL || _gtk_widget_get_parent (sibling) == (GtkWidget*)grid' failed

(idjc:19134): Gtk-WARNING **: Can't set a parent on a toplevel widget
activated ch 1
song title: 

activated ch 3
activated ch 4
entering stereo mode, ch 4
Failed to read playerdefaults file
Traceback (most recent call last):
  File "/usr/bin/idjc", line 32, in <module>
    exit(idjc.main())
  File "/usr/lib/idjc/site-packages/idjc/__init__.py", line 116, in main
    return maingui.main()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4311, in main
    run_instance = MainWindow()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4191, in __init__
    lambda s, f: idle_add(threadslock(self.destroy))
  File "/usr/lib/python3.5/signal.py", line 48, in signal
    return _int_to_enum(handler, Handlers)
  File "/usr/lib/python3.5/signal.py", line 30, in _int_to_enum
    return enum_klass(value)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
  File "/usr/lib/python3.5/site-packages/dbus/service.py", line 786, in __repr__
    if (self._object_path is not _MANY
AttributeError: 'MainWindow' object has no attribute '_object_path'
morfeo@unknown ~> JackTemporaryException : now quits...
Jack main caught signal 2
Released audio card Audio0
audio_reservation_finish

```

**Comment by leofiore** [comment]
last issue is the relevant one, and is #3. Closing this.
