### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute '_object_path'

### ISSUE THREAD

**Issue by leofiore** [radiocicletta/idjc-x#3]
citing @M0Rf30's previous [comments](https://github.com/radiocicletta/idjc-x/issues/1#issuecomment-269199602) in #1 :

```
Traceback (most recent call last):
  File "/usr/bin/idjc", line 32, in <module>
    exit(idjc.main())
  File "/usr/lib/idjc/site-packages/idjc/__init__.py", line 116, in main
    return maingui.main()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4311, in main
    run_instance = MainWindow()
  File "/usr/lib/idjc/site-packages/idjc/maingui.py", line 4191, in __init__
    lambda s, f: idle_add(threadslock(self.destroy))
  File "/usr/lib/python3.5/signal.py", line 48, in signal
    return _int_to_enum(handler, Handlers)
  File "/usr/lib/python3.5/signal.py", line 30, in _int_to_enum
    return enum_klass(value)
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
  File "/usr/lib/python3.5/site-packages/dbus/service.py", line 786, in __repr__
    if (self._object_path is not _MANY
AttributeError: 'MainWindow' object has no attribute '_object_path'
```

**Comment by leofiore** [comment]
Looks like the dbus object initialization fails for the MainWindow class. 
and looking at the first line in the log you posted in #2, i see this:

```
** (idjc:19134): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-0SUEvMdYIN: Connessione rifiutata
```

How did you configured/built/installed/run the application? can you please provide your ./configure options?

**Comment by M0Rf30** [comment]
```
./bootstrap
    ./configure \
        --prefix=/usr \
        --libexecdir=/usr/lib \
        --disable-static

```

**Comment by leofiore** [comment]
fe670c68de7e2dbdd7f2cff11828786fe40428f5 fix this problem. Tested on a freshly installed arch linux machine.

**Comment by M0Rf30** [comment]
Ok, now main gui works, but there are many cosmetic problems that I hope you'll fix. thanks man
